const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const sourcePath = path.join(root, 'node_modules', 'cobe', 'dist', 'index.esm.js');
const outputPath = path.join(root, 'assets', 'js', 'cobe.js');
const texturePath = path.join(root, 'assets', 'img', 'cobe-world.png');

const source = fs.readFileSync(sourcePath, 'utf8');

const textureMatch = source.match(/j\.src="data:image\/png;base64,([^"]+)"/);

if (!textureMatch) {
	throw new Error('Failed to extract embedded COBE texture.');
}

fs.mkdirSync(path.dirname(texturePath), {recursive: true});
fs.writeFileSync(texturePath, Buffer.from(textureMatch[1], 'base64'));

const loaderPattern = /let j=new Image;j.onload=\(\)=>\{([\s\S]*?)\},j\.src="data:image\/png;base64,[^"]+";/;

if (!loaderPattern.test(source)) {
	throw new Error('Failed to patch COBE texture loader.');
}

const patchedSource = source
	.replace(loaderPattern, (_, onloadBody) => {
		return 'const __cobeScript=document.currentScript'
			+ '||Array.from(document.scripts).find((script)=>script.src&&/\\/assets\\/js\\/cobe\\.js(?:\\?|$)/.test(script.src));'
			+ 'const __cobeTextureUrl=__cobeScript'
			+ '?new URL("../img/cobe-world.png",__cobeScript.src).href'
			+ ':new URL("assets/img/cobe-world.png",window.location.href).href;'
			+ 'let __cobeDestroyed=false;'
			+ 'let j=new Image;'
			+ 'j.crossOrigin="anonymous";'
			+ `j.onload=()=>{if(__cobeDestroyed){return;}${onloadBody};if(!__cobeDestroyed&&typeof te==="function"){te({});}},`
			+ 'j.onerror=()=>{if(!__cobeDestroyed){console.warn("[EarthView] Failed to load COBE texture:",__cobeTextureUrl)}},'
			+ 'j.src=__cobeTextureUrl;';
	})
	.replace('function te(t){', 'function te(t){if(__cobeDestroyed){return;}')
	.replace(
		'return te({markers:c,arcs:s}),{update:te,destroy:()=>{a.deleteBuffer(D),a.deleteBuffer(_),a.deleteBuffer(k),a.deleteBuffer(S),a.deleteProgram(w),C&&a.deleteProgram(C),F&&a.deleteProgram(F),$.r()}}};export{Pe as default};',
		'return te({markers:c,arcs:s}),{update:(e)=>{if(!__cobeDestroyed){te(e)}},destroy:()=>{if(__cobeDestroyed){return}__cobeDestroyed=true,j.onload=null,j.onerror=null,a.deleteBuffer(D),a.deleteBuffer(_),a.deleteBuffer(k),a.deleteBuffer(S),a.deleteProgram(w),C&&a.deleteProgram(C),F&&a.deleteProgram(F),$.r()}}};export{Pe as default};'
	)
	.replace(/export\{Pe as default\};\s*$/, 'return { default: Pe };');

const output = [
	'// Generated by `npm run build:cobe`.',
	'var COBE = (() => {',
	patchedSource,
	'})();',
	''
].join('\n');

fs.mkdirSync(path.dirname(outputPath), {recursive: true});
fs.writeFileSync(outputPath, output);

console.log(`Generated ${path.relative(root, outputPath)}`);
console.log(`Generated ${path.relative(root, texturePath)}`);
